import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Appbar from '../components/Appbar'
import Bottombar from '../components/Bottombar'
import Buttonadd from '../components/Buttonadd'
import dynamic from 'next/dynamic'
const Page = dynamic(() => import('../components/Page'))
const Onmind = dynamic(() => import('../components/Onmind'))

export default function Home({ posts, articles }) {
  return (
    <div className='header_page'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/lg.png" />
        <meta name="theme-color"content="rgb(0, 30, 60)"></meta>
      </Head>
      <main className='header_page'>
     <Appbar/>
     <Onmind/>
     <Buttonadd/>
       <Page posts={posts} />
    <Bottombar/>
      </main>
    </div>
  )
}


