import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Appbar from '../components/Appbar'
import Bottombar from '../components/Bottombar'
import Buttonadd from '../components/Buttonadd'
import Page from '../components/Page'
import { getSession, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { useRecoilState } from "recoil";

import { connectToDatabase } from "../util/mongodb";
import Account from './account'
import Form from './createpost'

export default function Home({ posts, articles }) {
  const router = useRouter();
  const { status } = useSession({
    required: true,
    onUnauthenticated() {
      // The user is not authenticated, handle it here.
      router.push("/account");
    },
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
     
     
     
      </Head>

      <main className={styles.main}>
   
     <Appbar/>
     <Buttonadd/>
       <Page posts={posts} />
    <Bottombar/>
      </main>
    </div>
  )
}


export async function getServerSideProps(context) {
  // Check if the user is authenticated on the server...
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: "/account",
      },
    };
  }

  // Get posts on SSR
  const { db } = await connectToDatabase();
  const posts = await db
    .collection("posts")
    .find()
    .sort({ timestamp: -1 })
    .toArray();

  return {
    props: {
      posts: posts.map((post) => ({
        _id: post._id.toString(),
       title: post.title,
      description: post. description,
        image: post.image,
        video: post.video,
       name: post.name,
       likes:post.likes,
       likeId:post.likeId,
      comments:post.comments,
        email: post.email,
        userImg: post.userImg,
        createdAt: post.createdAt,
        reposter:post.reposter,
      })),
    },
  };
}

