import Head from 'next/head'
import { connectToDatabase } from "../util/mongodb";
import dynamic from 'next/dynamic'
const Page = dynamic(() => import('./Page'))

export default function Render({ posts, articles }) {
  return (
    <div className='header_page'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/lg.png" />
        <meta name="theme-color"content="#2196f3"></meta>
      </Head>
      <main className='header_page'>
        <p>jxvhjbjdjhvjd</p>
       <Page posts={posts} />
      </main>
    </div>
  )
}

export async function getServerSideProps({ req, res,context }) {

  // Get posts on SSR
  const { db } = await connectToDatabase();
  const posts = await db
    .collection("posts")
    .find()
    .sort({ timestamp: -1 })
    .toArray();

  return {
    props: {
      posts: posts.map((post) => ({
        _id: post._id.toString(),
       title: post.title,
      description: post. description,
        image: post.image,
        video: post.video,
       name: post.name,
       likes:post.likes,
       likeId:post.likeId,
      comments:post.comments,
        // email: post.email,
        userImg: post.userImg,
        createdAt: post.createdAt,
        // reposter:post.reposter,
      })),
    },
  };
}

